### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by dereuromark** [ebrigham1/cakephp-error-email#2]
Tip:

    "cakephp/cakephp": ">=3.3.2 <4.0.0"

can be simplified using carot: `^3.2.2`

**Comment by ebrigham1** [comment]
I'm assuming you mean `^3.3.2` and not `^3.2.2`? I was also looking into supporting `>=3.0.0 <3.3.0`. I think I just need to change the instructions and not include the middleware in a new branch and figure out a tagging scheme, as I think 3.2.x and below just don't include the middleware error handling. Do people ever get stuck on minor versions/have trouble upgrading to where that would be worth doing?

**Comment by ebrigham1** [comment]
Updated here: 5a96a69b6cb383594ab34da315eaabd7e691405d

**Comment by dereuromark** [comment]
Yeah :) thats What I meant
