### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by AndreLZGava** [ebrigham1/cakephp-error-email#6]
I've cloned your plugin inside my plugins dir then I've made configurations like you say in the readme page, but my project don't work it gives me the message:

Fatal error: Uncaught Error: Class 'ErrorEmail\Error\ErrorHandler' not found in /var/www/html/app/config/bootstrap.php:122 Stack trace: #0 /var/www/html/app/vendor/cakephp/cakephp/src/Http/BaseApplication.php(61): require_once() #1 /var/www/html/app/vendor/cakephp/cakephp/src/Http/Server.php(70): Cake\Http\BaseApplication->bootstrap() #2 /var/www/html/app/webroot/index.php(37): Cake\Http\Server->run() #3 {main} thrown in /var/www/html/app/config/bootstrap.php on line 122

I'm loading the plugin in my bootstrap.php
and I've replaced default cakephp error handler by yours
and in my applicationphp error handermidleware I've done the same
in my app.php I've added configuration for default configuration

What may I have done wrong?

**Comment by ebrigham1** [comment]
Hi @AndreLZGava 

So it looks to me like you are running into a problem with autoloading. From reading your message it sounds like you're not installing the plugin via composer which means you would have to manually set up the autoloading for it in your composer.json file as per the instructions here: 

https://book.cakephp.org/3.0/en/plugins.html#autoloading-plugin-classes

So you would have to add a couple of lines to your composer.json file so your autoloading section looked something like this:

```
"autoload": {
    "psr-4": {
        "App\\": "src",
        "ErrorEmail\\": "./plugins/ErrorEmail/src"
    }
},
"autoload-dev": {
    "psr-4": {
        "App\\Test\\": "tests",
        "Cake\\Test\\": "./vendor/cakephp/cakephp/tests",
        "ErrorEmail\\Test\\": "./plugins/ErrorEmail/tests"
    }
},
```
The ErrorEmail lines are the important ones and you must make sure the path is correct to get to the src folder for the plugin so the autoloader knows how to find the classes for the plugin, the rest is just for context. Then you'll need to dump the autoloader with:
```
php composer.phar dumpautoload
```
or
```
composer dumpautoload
```
from inside your project root directory.

I would strongly recommend you install this plugin via composer as it is easier to use and will automatically handle the autoloading for you as well as dependency management. For instance if you install a version of the cakephp framework that isn't compatible with this plugin you would be notified when installing via composer where as you won't if you don't install via composer.

Let me know how this works out for you.

**Comment by AndreLZGava** [comment]
Cool, one of my projects I did this way and works fine, I don't like to use composer for install dependencies cause now in this project even using composer dumpautoload my app stop working delivering  me a 500 error from browser.

I'm looking for a solution, thanks for this help and congratulations for developing this plugin this is really usefull.

**Comment by ebrigham1** [comment]
What is the 500 error, can you look in your error log? This plugin can throw exceptions if its misconfigured in some way which will result in a 500 error. Does the 500 error still happen if you aren't using the plugin?

**Comment by AndreLZGava** [comment]
In error log: PHP Fatal error:  Uncaught Error: Class 'App\\Application' not found in /var/www/html/app/webroot/index.php:33\nStack trace:\n#0 {main}\n  thrown in /var/ww$$var/www/html/app/webroot/index.php on line 33

then I go back in history (git) I just tried composer dumpautoload an than the same error happens (500) in browser and in the log that error happens again.

**Comment by AndreLZGava** [comment]
I notice that after composer dumpautoload something happen to webroot/index.php this is getting Application class from a vendor file and not from src/application.php anymore. Both of them are class Application extens BaseApplication but application uses namespace App while in vendor it uses namespace as Composer\Console

**Comment by AndreLZGava** [comment]
I've solved that was just an error for my configurations, thanks for your help and congratulation for your develop this is very usefull
