### ISSUE TITLE
Replace deprecated 'here' attribute

### ISSUE THREAD

**Issue by pettrbalint** [ebrigham1/cakephp-error-email#8]
Is it possible to replace deprecated function call in Tempaltes/Email/html/error.ctp and exception.ctp ?

Should be used

`$this->request->getAtrribute('here')`

instead of currently used

`$this->request->here`

since this will soon be deprecated.

Thanks.

**Comment by ebrigham1** [comment]
Hi @pettrbalint thanks for letting me know about the here property deprecation, I've released a patch that uses `$this->request->getAttribute('here')` in place of `$this->request->here` in all templates and tagged it as version 1.2.3.

Thanks,
-Ethan
