### ISSUE TITLE
Replace deprecated methods setTemplate() and setLayout()

### ISSUE THREAD

**Issue by pettrbalint** [ebrigham1/cakephp-error-email#9]
Hi,
would it be possilbe to replace deprecated methods 
- **setTemplate()**
- **setLayout()**

in `src/Tratis/EmailThrowableTrait.php ` with
- **$email->viewBuilder()->setTemplate()** 
- **$email->viewBuilder()->setLayout()**

?

As Cake4 is approaching (and methods marked as deprecated are supposed to be removed in v3.8 according to roadmap), maybe there are more than just these two remaining.

Thank you.

**Comment by ebrigham1** [comment]
Hi @pettrbalint thanks again for letting me know about these deprecation, I've updated and tagged release 1.2.4 which takes care of these two.
